travis:
  secure:
    BINSTAR_TOKEN: SmX80e6oya1gCPxUoqsio8VuCWNmDp+dYytylHyLAIDLu7cOWYzHqkYEsKj64ntwy5Yy4u5LI43Vz5C2Qn/4nelIWfSO1KwnDu0LC6Uwd2Gqoi0zbok1EWF9103ZotIdZ32A854KWzqXowV2xkLIB9A1J/eS8SC/6YyYMEkM25q5uVKbrFTckdG6ICDHglUnQt7+XG8FalvgJkSO1BY3ZB/CIfENWsY3/gea+V5QQBLswZ7vmwXN1QOXQdfI1y2vQ6l7zqNj84W+G/bxXaJ47jXhPp1ZNAmsRCu2BwRk76YsTpy4AU/0FaxmENXSX/R0E8inuaErqVLyShe61RjrBpnQRDCSCzF9Zp/UCgOtJHNalN+DdrKCVSqENSEFv4Q8ewMkKrJS3H7kZyVQoytIim9Z7+dZUUwls+btHprZ9dVloiYGKyL4FkhtIB+Un7uVXXkC9Cj6sup7Cp9MojsENYLrmg0DPz7bkOL7NcGDhYKMtVcmLjT0pDqsTIXoEYYXz9r3zvOr1Y04wJvztvH5+kjVLk8M9rBhRb+2d+hSxiXJ+8BaLMjYHAMvydDS0cF37hXs55fgw4agiO9GyzpJHBh0VtQoUkF3Uwgh8l18NMHe7awOuakvo13cce7QMHH06kHJ6IVKRAhuMbLJ2Jv9Fh2V+Fw4YpYLS5d+TW9xhOs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
