travis:
  secure:
    BINSTAR_TOKEN: YU0vmL6B1O0Zl1S5GobMGI8eFiNxqJnSJXwfEUeBl/BgPS/CrSHT0lMG4Ez/3QHTo06w8ViDa0fYttznJ6/KzXSg8FjfdM2lkavVONSm1V3xGtOuMl0T/Km59nVx/hSAmjjWcRpgk3FR6lEkFVm/32xQhSN7liUXFF7w1BDRn6P6qaItozlABxFm0DTFv+kOch8Uwh7AS99Y7MFlE1myil5n1QzVw+XZhUeZZ0adQtKHX3TIV8YFnEAaVOg65lkuwL1bMH80mGqQ8UYWeQpj1Az7CGrtnev/Himvq/k7ljgpdumhbBy2KrbhdLOCnEm1osdsGPl78JSvNXxRWdAYkq/3vApt2O9zJdTdlSsK4OwVocjIBOOBIdAxZWR1gafuRQ0wL2MqrQ4mtIN3hbr6Uj4A5erbFyjjh6CUxvWGZqtOE8XjihwHyd14sbvQh6Z8w2QVa7HRfxIXdl7aMvP6TcbuzXBEXK3rO8Omdoc1Wti85MEexdhI3XcdbhJhJzRmk67glbQQp7PSCjsCHoWzCt7lQkWCZZpLY7iP4nSvZm/REHBZdLTtMdCXgs993Iwr7xStNavb81vXel8WVq2qjB2d/DnGRnPTQHVW2jz09kVKFlZgZGxWDO5pIP32zma6KOO/6yA+UATcQR310sD6V6kQvo4Q+PAWLRKZPWx+6ds=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
